stages:
  - PHP
  - Vagrant
  - Molecule

jobs:
  include:
    - &PHP

      os: linux

      dist: xenial

      cache:
        directories:
          - "$HOME/.composer/cache"

      language: php
  
      php: 7.2

      before_install:
        - phpenv config-rm xdebug.ini
        - composer self-update

      install:
        - composer install --no-interaction --no-progress --no-suggest --prefer-dist --optimize-autoloader

      script:
        - ./bin/phpcs
        - ./bin/phpstan analyse
        - ./bin/phpunit

    - <<: *PHP

      php: 7.3

    - <<: *PHP

      php: 7.4

    - &Vagrant

      os: windows

      language: php

      php: 7.2

      env: VIRTUAL_BOX_VERSION=5.2.34

      before_install:
        - choco install virtualbox --version $VIRTUAL_BOX_VERSION
        - choco install vagrant --version 2.2.6

      install:
        - composer install --no-interaction --no-progress --no-suggest --prefer-dist --optimize-autoloader

      script:
        - vagrant up

    - <<: *Vagrant

      env: VIRTUAL_BOX_VERSION=6.0.14
