stages:
  - PHP
  - Molecule

jobs:
  include:
    - &PHP

      stage: PHP

      os: linux

      dist: xenial

      cache:
        directories:
          - "$HOME/.composer/cache"

      language: php
  
      php: 7.2

      before_install:
        - phpenv config-rm xdebug.ini
        - composer self-update

      install:
        - composer install --no-interaction --no-progress --no-suggest --prefer-dist --optimize-autoloader

      script:
        - ./bin/phpcs
        - ./bin/phpstan analyse
        - ./bin/phpunit

    - <<: *PHP

      php: 7.3

    - <<: *PHP

      php: 7.4

    - &Molecule

      stage: Molecule

      os: linux

      dist: xenial

      cache:
        apt: true
        pip: true
        directories:
          - "$HOME/.composer/cache"

      language: php

      php: 7.2

      env:
        - VIRTUAL_BOX_VERSION=5.2 MOLECULE_PLATFORM=ubuntu:16.04
        - VIRTUAL_BOX_VERSION=5.2 MOLECULE_PLATFORM=ubuntu:18.04

      before_install:
        # Download and register Oracle VirtualBox keys
        - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
        - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
        # Add Oracle VirtualBox repository
        - sudo add-apt-repository "deb https://download.virtualbox.org/virtualbox/debian xenial contrib"
        # Update apt-get
        - sudo apt-get update -qq
        # Install Linux headers
        - sudo apt-get -y --force-yes install linux-headers-`uname -r`
        # Install VirtualBox
        - sudo apt-get install virtualbox-${VIRTUAL_BOX_VERSION}
        # Install Vagrant
        # Todo: install from a package repository, not from a hardcoded URL.s
        - curl -O https://releases.hashicorp.com/vagrant/2.2.6/vagrant_2.2.6_x86_64.deb
        - sudo dpkg -i vagrant_2.2.6_x86_64.deb

      install:
        - composer install --no-interaction --no-progress --no-suggest --prefer-dist --optimize-autoloader
        - pip install ansible==2.6.* docker molecule

      script:
        - vagrant status
        - molecule test

    - <<: *Molecule

      env:
        - VIRTUAL_BOX_VERSION=6.0 MOLECULE_PLATFORM=ubuntu:16.04
        - VIRTUAL_BOX_VERSION=6.0 MOLECULE_PLATFORM=ubuntu:18.04
