---
branches:
  only:
    - 3.x.x
    - /^\d+\.\d+\.\d+[-a-z0-9]*$/

stages:
  - PHP
  - Vagrant
  - Molecule
  - Code coverage

jobs:
  fast_finish: true
  allow_failures:
    - stage: Molecule
      env: MOLECULE_PLATFORM=ubuntu2004

  include:
    - &PHP

      stage: PHP

      os: linux

      dist: xenial

      cache:
        directories:
          - "$HOME/.composer/cache"

      language: php
  
      php: 7.2

      env: PREFER_LOWEST=--prefer-lowest

      before_install:
        - phpenv config-rm xdebug.ini
        # Some tests run Composer via command line. It's not possible to require
        # a package in the detached state. Checkout to a branch to workaround
        # this.
        - git checkout -b test

      install:
        - composer update --no-progress --no-suggest --prefer-dist $PREFER_LOWEST --optimize-autoloader

      script:
        - ./vendor/bin/phpcs
        - ./vendor/bin/phpstan analyse
        - ./vendor/bin/phpunit

    - <<: *PHP

      php: 7.3

      env: PREFER_LOWEST=

    - <<: *PHP

      php: 7.4

      env: PREFER_LOWEST=

    - &Vagrant

      stage: Vagrant

      os: linux

      dist: xenial

      cache:
        apt: true

      language: php

      php: 7.2

      env: VIRTUAL_BOX_VERSION=5.2

      before_install:
        - phpenv config-rm xdebug.ini
        # Download and register Oracle VirtualBox keys
        - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
        - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
        # Add Oracle VirtualBox repository
        - sudo add-apt-repository "deb https://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib"
        # Add Vagrant PPA (unofficial)
        - sudo add-apt-repository -y ppa:tiagohillebrandt/vagrant
        # Update apt-get
        - sudo apt-get update -qq
        # Install Linux headers
        - sudo apt-get -y --force-yes install linux-headers-`uname -r`
        # Install VirtualBox
        - sudo apt-get install virtualbox-${VIRTUAL_BOX_VERSION}
        # Install Vagrant
        - sudo apt-get install vagrant

      install:
        - composer install --no-interaction --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-dev

      script:
        - vagrant status

    - <<: *Vagrant

      env: VIRTUAL_BOX_VERSION=6.0

    - <<: *Vagrant

      env: VIRTUAL_BOX_VERSION=6.1

    - &Molecule

      stage: Molecule

      os: linux

      dist: xenial

      cache:
        pip: true
        directories:
          - "$HOME/.composer/cache"

      language: python

      python: 3.6

      env: MOLECULE_PLATFORM=ubuntu1604

      before_install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

      install:
        - composer install --no-interaction --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-dev
        - pip install ansible==2.9.* ansible-lint docker yamllint molecule==3.*

      script:
        - molecule test

    - <<: *Molecule

      env: MOLECULE_PLATFORM=ubuntu1804

    - <<: *Molecule

      env: MOLECULE_PLATFORM=ubuntu2004

    - &CodeCoverage

      stage: Code Coverage

      os: linux

      dist: xenial

      cache:
        directories:
          - "$HOME/.composer/cache"

      language: php

      php: 7.2

      before_install:
        # Some tests run Composer via command line. It's not possible to require
        # a package in the detached state. Checkout to a branch to workaround
        # this.
        - git checkout -b test

      install:
        - composer install --no-interaction --no-progress --no-suggest --prefer-dist --optimize-autoloader

      script:
        - ./vendor/bin/phpunit --testsuite=unit --coverage-clover=coverage.xml

      after_success:
        - bash <(curl -s https://codecov.io/bash)
