stages:
  - PHP
  - Vagrant
  - Molecule

jobs:
  include:
    - &PHP

      dist: xenial

      cache:
        directories:
          - "$HOME/.composer/cache"

      language: php
  
      php: 7.2

      before_install:
        - xdebug-disable
        - composer self-update

      install:
        - composer install --no-interaction --no-progress --no-suggest

      script:
        - ./bin/phpcs
        - ./bin/phpstan analyse
        - ./bin/phpunit

    - <<: *PHP

      php: 7.3

    - <<: *PHP

      php: 7.4
