---
# This is exact copy of main playbook, except oefenweb.swapfile is skipped
# because it's not possible to test it on Travis CI. Also we manually add
# vagrant user as it does not exist in Docker.
- hosts: all
  become: true

  roles:
    - ../../provisioning/roles/draft
    - oefenweb.swapfile
    - ../../provisioning/roles/git_config
    - ../../provisioning/roles/apache2
    - geerlingguy.mysql
    - geerlingguy.mailhog
    - T2L.php
    - T2L.composer
    - T2L.java
    - T2L.solr
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - ../../default.vm-settings.yml
