---
- src: oefenweb.swapfile
  version: v2.0.24
- src: geerlingguy.mailhog
  version: 2.2.0
- src: geerlingguy.mysql
  version: 2.9.5
- src: T2L.php
  version: 1.2.1
- src: T2L.composer
  version: 2.0.2
- src: T2L.java
  version: 1.2.0
- src: T2L.solr
  version: 2.1.1
