---
- src: oefenweb.swapfile
  version: v2.0.29
- src: geerlingguy.mailhog
  version: 2.2.0
- src: geerlingguy.mysql
  version: 3.3.0
- src: T2L.php
  version: 1.3.1
- src: T2L.composer
  version: 2.0.2
- src: T2L.java
  version: 1.3.1
- src: T2L.solr
  version: 2.2.1
