name: CI

on:
  pull_request:
  push:
    branches:
      - 3.x.x
    tags:

jobs:
  php:
    name: PHP

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - '7.2'
          - '7.3'
          - '7.4'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Some tests run Composer via command line. It's not possible to require
      # a package in the detached state. Checkout to a branch to workaround
      # this.
      - name: Checkout to a branch
        run: git checkout -b test

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          tools: composer:v1, prestissimo
      
      - name: Install dependencies
        run: composer update --no-progress --prefer-dist --optimize-autoloader

      - name: Coding standards
        run: vendor/bin/phpcs

      - name: Static Code Analysis
        run: vendor/bin/phpstan analyse

      - name: Tests
        run: vendor/bin/phpunit

  vagrant:
    name: Molecule with Vagrant

    runs-on: macos-latest

    env:
      OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES

    strategy:
      matrix:
        molecule-platform:
          - xenial64
          - bionic64
          - focal64

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: 7.4
          tools: composer:v1, prestissimo

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-dev

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Molecule and it's dependencies
        run: pip install ansible==2.9.* ansible-lint yamllint molecule~=3.1 python-vagrant molecule-vagrant

      - name: Run Molecule tests
        run: molecule test
        env:
          MOLECULE_PLATFORM: ${{ matrix.molecule-platform }}

  code-coverage:
    name: Code Coverage

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Some tests run Composer via command line. It's not possible to require
      # a package in the detached state. Checkout to a branch to workaround
      # this.
      - name: Checkout to a branch
        run: git checkout -b test

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          php-version: 7.4
          tools: composer:v1, prestissimo

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Collect code coverage
        run: vendor/bin/phpunit --testsuite=unit --coverage-clover=coverage.xml

      - name: Send code coverage report to Codecov.io
        uses: codecov/codecov-action@v1
        with:
         file: coverage.xml
