name: CI

on:
  pull_request:
  push:
    branches:
      - 3.x.x
    tags:

jobs:
  php:
    name: PHP

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.2
          - 7.3
          - 7.4

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Some tests run Composer via command line. It's not possible to require
      # a package in the detached state. Checkout to a branch to workaround
      # this.
      - name: Checkout to a branch
        run: git checkout -b test

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          tools: composer:v1, prestissimo
      
      - name: Install dependencies
        run: composer update --no-progress --prefer-dist --optimize-autoloader

      - name: Coding standards
        run: vendor/bin/phpcs

      - name: Static Code Analysis
        run: vendor/bin/phpstan analyse

      - name: Tests
        run: vendor/bin/phpunit

  vagrant:
    name: Vagrant

    runs-on: ubuntu-latest

    strategy:
      matrix:
        virtual-box-version:
          - 5.2
          - 6.0
          - 6.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install VirtualBox
        run: |
          # Download and register Oracle VirtualBox keys
          wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
          wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
          # Add Oracle VirtualBox repository
          add-apt-repository "deb https://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib"
          # Update apt-get
          apt-get update -qq
          # Install Linux headers
          apt-get -y --force-yes install linux-headers-`uname -r`
          # Install VirtualBox
          apt-get install virtualbox-${VIRTUAL_BOX_VERSION}

      - name: Install Vagrant
        run: |
          # Add Vagrant PPA (unofficial)
          add-apt-repository -y ppa:tiagohillebrandt/vagrant
          # Update apt-get
          apt-get update -qq
          # Install Vagrant
          apt-get install vagrant

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: 7.4
          tools: composer:v1, prestissimo

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-dev

      - name: Check Vagrant status
        run: vagrant status
