name: CI

on:
  pull_request:
  push:
    branches:
      - 3.x.x
    tags:

jobs:
  php:
    name: PHP

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.2
          - 7.3
          - 7.4
        composer-version:
          - 1
          - 2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
      
      - name: Install dependencies
        uses: php-actions/composer@v4
        with:
          php_version: ${{ matrix.php-version }}
          composer_version: ${{ matrix.composer-version }}

      - name: Coding standards
        run: vendor/bin/phpcs

      - name: Static Code Analysis
        run: vendor/bin/phpstan analyse

      - name: Tests
        run: vendor/bin/phpunit
