name: CI

on:
  pull_request:
  push:
    branches:
      - 3.x.x
    tags:

jobs:
  php:
    name: PHP

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.2
          - 7.3
          - 7.4

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          tools: composer:v1, prestissimo
      
      - name: Install dependencies
        run: composer update --no-progress --prefer-dist --optimize-autoloader

      - name: Coding standards
        run: vendor/bin/phpcs

      - name: Static Code Analysis
        run: vendor/bin/phpstan analyse

      - name: Tests
        run: vendor/bin/phpunit
